version: '3.8'
services:


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    env_file:
      - docker/zookeeper.env
    ports:
      - "22181:2181"
    networks:
      my_net:

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    env_file:
      - docker/kafka.env
    networks:
      my_net:


  service-db:
    image: postgres:15-alpine3.19
    env_file:
      - docker/db.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d summer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - my_net
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    env_file:
      - docker/minio.env
    volumes:
      - minio_data:/data
      - minio_certs:/certs
      - minio_files:/file-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - my_net


volumes:
  db-data:
  minio_data:
  minio_certs:
  minio_files:

networks:
  my_net:
    driver: bridge