spring:
  application:
    name: trelo_liquibase


  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: on
  datasource:
    driver-class-name: org.postgresql.Driver
    username: danila
    password: fedin
    url: jdbc:postgresql://localhost:5432/trelo_liquibase


  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver