spring:
  application:
    name: trelo_client

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      url: redis://localhost:6379
      time-to-live: 900000

client:
  server:
    root-uri: http://localhost:8080

server:
  port: 8081

kafka:
  topic:
    desk: desk
    column: column
    task: task